### ISSUE TITLE
Not all devices returned with get inventory devices

### ISSUE THREAD

**Issue by raoulmorik** [dannywade/dnac-sidekick#1]
We have over 1700 devices in DNA Center, but the output only shows the first 500, which is the default paging size. There is a parameter in the request to get the next 500 and so on (&offset=500, &offset=1000 .....).

By the way, tested with DNA Center 2.2.3.6 - works great

**Comment by dannywade** [comment]
Thanks for opening an issue! The pagination makes sense. I didn't catch this since there were only about 5 devices available in the sandbox environment. I'll look into the pagination and add DNAC 2.2.3.6 to the list of compatible versions.

Maybe instead of printing all 1700 devices to the screen, would it make sense to have the option to output to a CSV, JSON, or another data format? I just don't want the terminal to get blasted with output and require the user to scroll forever to see their inventory.

**Comment by raoulmorik** [comment]
For me personaly, both would make sense - showing all on screen and an export option to csv and/or json. Maybe with an optional parameter to this function?

**Comment by dannywade** [comment]
Got it. I'll take a look into it!

**Comment by dannywade** [comment]
@raoulmorik I believe I solved the issue. Since I don't have a sandbox environment with that many devices to test, do you mind checking out the `1-not-all-devices-returned-with-get-inventory-devices` branch and running it locally? Feel free to review the code as well. Essentially, the tool will figure out how many devices you have in inventory and make multiple API calls to gather all your devices using limits and offsets. All your devices should then print out in the terminal.

I'm still working on an export option, but that may be a separate effort, as I would want that feature across more commands.

**Comment by raoulmorik** [comment]
@dannywade I cloned the branch and ran it with pythin3 cli.py get inventory devices - but still not working, getting only 500 devices reported back.

**Comment by dannywade** [comment]
@raoulmorik I made some changes. Please try again when you get a chance.

**Comment by raoulmorik** [comment]
@dannywade Sorry to say, but still getting only 500 devices after doing a git pull and running python3 cli.py get inventory devices

**Comment by dannywade** [comment]
@raoulmorik I changed the logic again and added some print statements (not best practice!) to debug. If you get any errors or only the first 500 devices print out, could you please copy and paste just the print statement output? All the print statement output should be above the table output and will not have any sensitive info - just the number of total pages (# of calls to make), the offset, and some other output to figure out where a failure may occur.

**Comment by raoulmorik** [comment]
I cloned the repo with git clone -b 1-not-all-devices-returned-with-get-inventory-devices https://github.com/dannywade/dnac-sidekick.git and ran again - no prints on the screen, only the same values as on my last try (500).

**Comment by dannywade** [comment]
Can you clone the repo, checkout the branch with `git checkout origin/1-not-all-devices-returned-with-get-inventory-devices`, and test again? If that still doesn't work, can you include the output of `git log --oneline`? I want to make sure you have the latest updates.

**Comment by raoulmorik** [comment]
xxxx@xxxxxx:~/test_dna_sidekick/dnac-sidekick# git log --oneline
30a2b03 (HEAD, origin/1-not-all-devices-returned-with-get-inventory-devices) Revert "added CONTRIBUTING.md" - need to rewrite
24a4f4a added print statements for debugging
9a9cc0b fixed paging loop for long device lists
d2267f5 added CONTRIBUTING.md
f3a5e1d added logic to offset and make multiple calls for larger device inventories
5913ee3 (origin/main, origin/HEAD, main) updated README - added DNAC version and DevNet badge
31a9ddc Merge pull request #2 from ecoen66/main
08f463e Update README.md
0cdc2be updated README - fixed typos
009b8f7 bumped version 0.1.0 -> 0.1.1
1d86f7f (tag: v0.1.1) issues with click context - changed instructions to manually set env vars
a6bb717 (tag: v0.1.0) updated readme and added imgs of sample output
feffe4d added examples to readme
fcf3bbb removed ability to search client health via MAC address and updated readme
e475d5b added some extra URL logic and updated 'get licenses' docstring
e8b600b added tests for device licensing
48d2ba2 added network license level and ability to pull license info for every device
7433507 getting single device license working
bb2d685 fixed entrypoint command
decd525 fixed readme and command runner docstring
4bf9cb3 updated to .gitignore to ignore dist folder
5d542d6 added badges to readme
728af25 Update python-package.yml
f85da43 added python 3.8 to pyproject.toml
0bba87f Merge branch 'main' of https://github.com/dannywade/dnac-sidekick
2d0b753 fixed testing and readme
0fbb7a6 added GH actions to test app
021352e updated readme and added entrypoint to pyproject.toml
523e99f added poetry and removed pycache
295b254 formatted with black
886305a added ability to use command runner and more unit tests
8023e0c reorganized project to be more modular and added context to commands
6d54230 Initial commit


I uninstalled the PIP Package, built it again with poetry and ran it. Now it seems to work:

 /xxx/.local/bin/poetry run python cli.py get inventory devices
Getting information...
Total pages: 4
Page: 0
Calculated offset: 0
More devices added!
Page: 1
Calculated offset: 500
More devices added!
Page: 2
Calculated offset: 1000
More devices added!
Page: 3
Calculated offset: 1500
More devices added!
Length of device list: 1715

and i get a bigger list :-)

**Comment by dannywade** [comment]
Sweet, that's great to hear! So everything looks good? All your devices print to your terminal? If so, I'll remove the print statements and merge it ASAP.

**Comment by raoulmorik** [comment]
In a rough review, all devices are there. Thank you for taking care on this.

**Comment by dannywade** [comment]
No problem. Thanks for bringing it to my attention!
